name: CI

on: [push, pull_request]

jobs:
  ts-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install and build
        run: |
          npm install
          npm run build
